version: "3"
services:
  install:
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"
  build: 
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run build"  
  test:
    image: node:18.15
    ports:
      - "8087:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run test"
  serve:
    image: node:18.15
    ports:
      - "8082:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app && npm run serve"         
  dev:
    #docker-compose run --rm dev bash
    user: node
    image: node:18.15
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true